// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtXBXLmGsGj93aUZaggdSeemn_1w8iJsU',
    appId: '1:832853840803:web:379e2d0dd3bea0af5fc016',
    messagingSenderId: '832853840803',
    projectId: 'makan-44787',
    authDomain: 'makan-44787.firebaseapp.com',
    storageBucket: 'makan-44787.firebasestorage.app',
    measurementId: 'G-7DSRTNRDJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHV829phQOC_IYxP7vcvnYnuD14fFUAvg',
    appId: '1:832853840803:android:03f47554b19327f65fc016',
    messagingSenderId: '832853840803',
    projectId: 'makan-44787',
    storageBucket: 'makan-44787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVe2hcrkkOAV7SsuYjY5Etauj5zxl1Scc',
    appId: '1:832853840803:ios:5027e71f81c2171a5fc016',
    messagingSenderId: '832853840803',
    projectId: 'makan-44787',
    storageBucket: 'makan-44787.firebasestorage.app',
    iosBundleId: 'com.example.makan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVe2hcrkkOAV7SsuYjY5Etauj5zxl1Scc',
    appId: '1:832853840803:ios:5027e71f81c2171a5fc016',
    messagingSenderId: '832853840803',
    projectId: 'makan-44787',
    storageBucket: 'makan-44787.firebasestorage.app',
    iosBundleId: 'com.example.makan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtXBXLmGsGj93aUZaggdSeemn_1w8iJsU',
    appId: '1:832853840803:web:a46d841e687f57605fc016',
    messagingSenderId: '832853840803',
    projectId: 'makan-44787',
    authDomain: 'makan-44787.firebaseapp.com',
    storageBucket: 'makan-44787.firebasestorage.app',
    measurementId: 'G-1RYLW7BT98',
  );
}
